# Sentinel-2 download settings

# collection
collection: "sentinel-2-l2a"

# area of interest
aoi: "data/aoi.geojson"

# date range
date_from: "2026-07-01"
date_to: "2026-07-31"

# maximum acceptable cloud cover (%)
max_cloud_cover: 20

# Sentinel-2 bands to download
bands:
  - B01
  - B02
  - B03
  - B04
  - B05
  - B06
  - B07
  - B08
  - B8A
  - B09
  - B11
  - B12

# data directory
data_path: "data"

# raw data directory
raw_data_path: "data/raw"

# processed data directory
data_processed_path: "data/processed"

# output directory
output_path: "outputs"

# indices directory
indices_path: "outputs/indices"